version: 2.1
orbs:
  node: circleci/node@3.0.1
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
      - run: npm run build
      - run: npm run test
      - persist_to_workspace:
          root: ~/project
          paths:
            - dist
  publish:
    executor:
      name: node/default
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/project/.npmrc
      - run: npm publish ~/project/dist --access public

workflows:
    build-and-test:
      jobs:
        - build-and-test:
            filters:
              tags:
                only: /.*/
        - publish:
            requires:
              - build-and-test
            filters:
              tags:
                only: /.*/
              branches:
                ignore: /.*/
