import {
  Access,
  Account,
  Action,
  Admin_name,
  Admin_password,
  After,
  All,
  Allow_duplicate,
  Allowed_IP_List,
  Alter,
  And,
  Any,
  Api_allowed_prefixes,
  Api_aws_role_arn,
  Api_blocked_prefixes,
  Api_key,
  Api_provider,
  Api,
  Application,
  Apply,
  As,
  Asc,
  At,
  Attach,
  Auto_ingest,
  Auto_refresh_materialized_views_on_secondary,
  Auto,
  Autoincrement,
  Avro,
  Aws_api_gateway,
  Aws_private_api_gateway,
  Azure_ad_application_id,
  Azure_api_management,
  Azure_tenant_id,
  Azure,
  Base64,
  Before,
  Bernoulli,
  Between,
  Binary_as_text,
  Binary_format,
  Binary,
  Block,
  Blocked_IP_List,
  Boolean,
  Brotli,
  Business_critical,
  By,
  Bz2,
  Called,
  Caller,
  Cascade,
  Case_insensitive,
  Case_sensitive,
  Case,
  Cast,
  Change_tracking,
  Channel,
  Char,
  Character,
  Clone,
  Cluster,
  Collate,
  Columns,
  Comment,
  Commit,
  Compression,
  Connect_by_root,
  Connect,
  Connection,
  Constraint,
  Continue,
  Copy,
  Create,
  Credit_quota,
  Cross,
  Csv,
  Cube,
  Current,
  D,
  Daily,
  Data_retention_time_in_days,
  Data,
  Database,
  Databases,
  Date_format,
  Datetime,
  Day,
  Dec,
  Decimal,
  Default_ddl_collation,
  Default,
  Deferrable,
  Deferred,
  Deflate,
  Delete,
  Desc,
  Describe,
  Disable_auto_convert,
  Disable_snowflake_data,
  Disable,
  Distinct,
  Do,
  Drop,
  Edition,
  Else,
  Email,
  Empty_field_as_null,
  Enable_octal,
  Enable,
  Enabled,
  Encoding,
  End_timestamp,
  End,
  Enforce_length,
  Enforced,
  Enterprise,
  Error_on_column_count_mismatch,
  Escape_unenclosed_field,
  Escape,
  Except,
  Exchange,
  Execute,
  Execution,
  Exists,
  External,
  Extract,
  False,
  Fetch,
  Field_delimiter,
  Field_optionally_enclosed_by,
  File_extension,
  File,
  First_name,
  First,
  Fn,
  Following,
  For,
  Force,
  Foreign,
  Format_name,
  Format,
  Formats,
  Frequency,
  From,
  Full,
  Function,
  Functions,
  Future,
  Gcs,
  Get,
  Global,
  Google_api_gateway,
  Google_audience,
  Grant,
  Grants,
  Group,
  Grouping,
  Gzip,
  Having,
  Hex,
  History,
  Hour,
  Identity,
  If,
  Ignore_utf8_errors,
  Ilike,
  Immediate,
  Immediately,
  Immutable,
  Import,
  Imported,
  In,
  Increment,
  Initiallly,
  Inner,
  Input,
  Insert,
  Integration,
  Integrations,
  Intersect,
  Into,
  Is,
  Join,
  Json,
  Key,
  Language,
  Last_name,
  Last,
  Lateral,
  Left,
  Like,
  Limit,
  List,
  Local,
  Lzo,
  Manage,
  Managed,
  Masking,
  Match_by_column_name,
  Match,
  Materialized,
  Max_data_extension_time_in_days,
  Minute,
  Modify,
  Monitor,
  Month,
  Monthly,
  Must_change_password,
  Must,
  Natural,
  Network,
  Networks,
  Never,
  Next,
  No,
  None,
  Norely,
  Not,
  Notification,
  Notify,
  Novalidate,
  Null_if,
  Null,
  Nulls,
  Number,
  Numeric,
  Of,
  Offset,
  Oj,
  On_error,
  On,
  Only,
  Operate,
  Option,
  Or,
  Orc,
  Order,
  Organization,
  Outer,
  Over,
  Override,
  Overwrite,
  Owner,
  Ownership,
  Parquet,
  Partial,
  Partition,
  Percent,
  Pipe,
  Pipes,
  Policies,
  Policy,
  Preceding,
  Precision,
  Preserve_space,
  Primary,
  Prior,
  Privileges,
  Procedure,
  Procedures,
  Purge,
  Qualify,
  Range,
  Raw_deflate,
  Read,
  Reader,
  Record_delimiter,
  Recursive,
  References,
  Regexp,
  Region_group,
  Region,
  Rely,
  Repeatable,
  Replace_invalid_characters,
  Replace,
  Replica,
  Replication,
  Resource,
  Restrict,
  Restrictions,
  Resume,
  Return_failed_only,
  Returns,
  Revoke,
  Right,
  Role,
  Rollback,
  Rollup,
  Row,
  Rows,
  S3,
  Sample,
  Schema,
  Schemas,
  Second,
  Secure,
  Security,
  Seed,
  Select,
  Semi,
  Sequence,
  Sequences,
  Session,
  Set,
  Sets,
  Share,
  Show,
  Simple,
  Size_limit,
  Skip_blank_lines,
  Skip_byte_order_mark,
  Skip_file,
  Skip_header,
  Snappy_compression,
  Snappy,
  Stage_copy_options,
  Stage_file_format,
  Stage,
  Stages,
  Standard,
  Start_timestamp,
  Start,
  Starts,
  Statement,
  Storage,
  Stream,
  Streams,
  Strict,
  String,
  Strip_null_values,
  Strip_outer_array,
  Strip_outer_element,
  Support,
  Suspend_immediate,
  Suspend,
  System,
  T,
  Table,
  Tables,
  Tablesample,
  Tag,
  Task,
  Tasks,
  Temp,
  Template,
  Temporary,
  Terse,
  Text,
  Then,
  Time_format,
  Timestamp_format,
  Timestamp_ltz,
  Timestamp_ntz,
  Timestamp_tz,
  Timestamp,
  Timestampltz,
  Timestampntz,
  Timestamptz,
  To,
  Top,
  Transient,
  Triggers,
  Trim_space,
  True,
  Truncate,
  Truncatecolumns,
  Try_cast,
  Ts,
  Type,
  Unbounded,
  Union,
  Unique,
  Unpivot,
  Update,
  Url,
  Usage,
  Use,
  User,
  Using,
  Utf8,
  Validate_utf8,
  Validate,
  Values,
  Varbinary,
  Varchar,
  Varying,
  View,
  Views,
  Volatile,
  Warehouse,
  Weekly,
  When,
  Where,
  With,
  Without,
  X,
  Xml,
  Year,
  Yearly,
  Zone,
  Zstd,
} from "./parser.terms.js";

const keywordTokens = {
  access: Access,
  admin_name: Admin_name,
  admin_password: Admin_password,
  after: After,
  all: All,
  allow_duplicate: Allow_duplicate,
  allowed_ip_list: Allowed_IP_List,
  and: And,
  any: Any,
  api_allowed_prefixes: Api_allowed_prefixes,
  api_aws_role_arn: Api_aws_role_arn,
  api_blocked_prefixes: Api_blocked_prefixes,
  api_key: Api_key,
  api_provider: Api_provider,
  api: Api,
  apply: Apply,
  as: As,
  asc: Asc,
  at: At,
  attach: Attach,
  auto_ingest: Auto_ingest,
  auto_refresh_materialized_views_on_secondary:
  Auto_refresh_materialized_views_on_secondary,
  auto: Auto,
  autoincrement: Autoincrement,
  avro: Avro,
  aws_api_gateway: Aws_api_gateway,
  aws_private_api_gateway: Aws_private_api_gateway,
  azure_ad_application_id: Azure_ad_application_id,
  azure_api_management: Azure_api_management,
  azure_tenant_id: Azure_tenant_id,
  base64: Base64,
  before: Before,
  bernoulii: Bernoulli,
  between: Between,
  binary_as_text: Binary_as_text,
  binary_format: Binary_format,
  binary: Binary,
  block: Block,
  blocked_ip_list: Blocked_IP_List,
  boolean: Boolean,
  brotli: Brotli,
  business_critical: Business_critical,
  by: By,
  bz2: Bz2,
  called: Called,
  caller: Caller,
  cascade: Cascade,
  case_insensitive: Case_insensitive,
  case_sensitive: Case_sensitive,
  case: Case,
  cast: Cast,
  change_tracking: Change_tracking,
  char: Char,
  character: Character,
  clone: Clone,
  cluster: Cluster,
  collate: Collate,
  compression: Compression,
  connect_by_root: Connect_by_root,
  connect: Connect,
  connection: Connection,
  constraint: Constraint,
  continue: Continue,
  copy: Copy,
  create: Create,
  credit_quota: Credit_quota,
  cross: Cross,
  csv: Csv,
  cube: Cube,
  current: Current,
  daily: Daily,
  data_retention_time_in_days: Data_retention_time_in_days,
  databases: Databases,
  date_format: Date_format,
  datetieme: Datetime,
  dec: Dec,
  decimal: Decimal,
  default: Default,
  deferrable: Deferrable,
  Deferred: Deferred,
  deflate: Deflate,
  delete: Delete,
  desc: Desc,
  describe: Describe,
  disable_auto_convert: Disable_auto_convert,
  disable_snowflake_data: Disable_snowflake_data,
  disable: Disable,
  distinct: Distinct,
  do: Do,
  drop: Drop,
  edition: Edition,
  else: Else,
  empty_field_as_null: Empty_field_as_null,
  enable_octal: Enable_octal,
  enable: Enable,
  encoding: Encoding,
  end_timestamp: End_timestamp,
  end: End,
  enforce_length: Enforce_length,
  enforced: Enforced,
  enterprise: Enterprise,
  error_on_column_count_mismatch: Error_on_column_count_mismatch,
  escape_unenclosed_field: Escape_unenclosed_field,
  escape: Escape,
  except: Except,
  exchange: Exchange,
  execute: Execute,
  execution: Execution,
  exists: Exists,
  extact: Extract,
  external: External,
  false: False,
  fetch: Fetch,
  field_delimiter: Field_delimiter,
  field_optionally_enclosed_by: Field_optionally_enclosed_by,
  file_extension: File_extension,
  file: File,
  first: First,
  fn: Fn,
  following: Following,
  for: For,
  force: Force,
  foreign: Foreign,
  format_name: Format_name,
  format: Format,
  formats: Formats,
  frequency: Frequency,
  from: From,
  full: Full,
  function: Function,
  functions: Functions,
  future: Future,
  get: Get,
  global: Global,
  google_api_gateway: Google_api_gateway,
  google_audience: Google_audience,
  grant: Grant,
  grants: Grants,
  group: Group,
  group: Group,
  grouping: Grouping,
  gzip: Gzip,
  having: Having,
  hex: Hex,
  history: History,
  if: If,
  ignore_utf8_errors: Ignore_utf8_errors,
  immediate: Immediate,
  immediate: Immediate,
  immediately: Immediately,
  immutable: Immutable,
  import: Import,
  imported: Imported,
  in: In,
  increment: Increment,
  initiallly: Initiallly,
  inner: Inner,
  insert: Insert,
  integrations: Integrations,
  intersect: Intersect,
  into: Into,
  is: Is,
  join: Join,
  json: Json,
  language: Language,
  last: Last,
  lateral: Lateral,
  like: Like,
  limit: Limit,
  list: List,
  local: Local,
  lzo: Lzo,
  manage: Manage,
  managed: Managed,
  masking: Masking,
  match_by_column_name: Match_by_column_name,
  match: Match,
  max_data_extension_time_in_days: Max_data_extension_time_in_days,
  modify: Modify,
  monitor: Monitor,
  monthly: Monthly,
  must: Must,
  natural: Natural,
  network: Network,
  networks: Networks,
  never: Never,
  next: Next,
  no: No,
  none: None,
  norely: Norely,
  not: Not,
  notification: Notification,
  notify: Notify,
  novalidate: Novalidate,
  null_if: Null_if,
  nulls: Nulls,
  number: Number,
  numeric: Numeric,
  of: Of,
  offset: Offset,
  oj: Oj,
  on_error: On_error,
  on: On,
  only: Only,
  operate: Operate,
  option: Option,
  or: Or,
  orc: Orc,
  outer: Outer,
  over: Over,
  override: Override,
  overwrite: Overwrite,
  ownership: Ownership,
  parquet: Parquet,
  partial: Partial,
  partition: Partition,
  pipe: Pipe,
  pipes: Pipes,
  Preceding: Preceding,
  precsion: Precision,
  preserve_space: Preserve_space,
  primary: Primary,
  prior: Prior,
  privileges: Privileges,
  procedure: Procedure,
  procedures: Procedures,
  purge: Purge,
  qualify: Qualify,
  range: Range,
  raw_deflate: Raw_deflate,
  read: Read,
  reader: Reader,
  record_delimiter: Record_delimiter,
  recursive: Recursive,
  references: References,
  region_group: Region_group,
  rely: Rely,
  repeatable: Repeatable,
  replace_invalid_characters: Replace_invalid_characters,
  replace: Replace,
  replica: Replica,
  replication: Replication,
  resource: Resource,
  restrict: Restrict,
  restrictions: Restrictions,
  restrictions: Restrictions,
  return_failed_only: Return_failed_only,
  returns: Returns,
  revoke: Revoke,
  right: Right,
  rollback: Rollback,
  rollup: Rollup,
  row: Row,
  rows: Rows,
  s3: S3,
  sample: Sample,
  schemas: Schemas,
  second: Second,
  seed: Seed,
  select: Select,
  semi: Semi,
  sequence: Sequence,
  sequences: Sequences,
  session: Session,
  set: Set,
  sets: Sets,
  share: Share,
  show: Show,
  simple: Simple,
  size_limit: Size_limit,
  skip_blank_lines: Skip_blank_lines,
  skip_byte_order_mark: Skip_byte_order_mark,
  skip_file: Skip_file,
  skip_header: Skip_header,
  snappy_compression: Snappy_compression,
  snappy: Snappy,
  stage_copy_options: Stage_copy_options,
  stage_file_format: Stage_file_format,
  stages: Stages,
  standard: Standard,
  start_timestamp: Start_timestamp,
  start: Start,
  starts: Starts,
  statement: Statement,
  storage: Storage,
  stream: Stream,
  streams: Streams,
  strict: Strict,
  string: String,
  strip_null_values: Strip_null_values,
  strip_outer_array: Strip_outer_array,
  strip_outer_element: Strip_outer_element,
  support: Support,
  suspend_immediate: Suspend_immediate,
  suspend: Suspend,
  system: System,
  t: T,
  table: Table,
  tables: Tables,
  tablesample: Tablesample,
  task: Task,
  tasks: Tasks,
  temp: Temp,
  template: Template,
  temporary: Temporary,
  terse: Terse,
  text: Text,
  then: Then,
  time_format: Time_format,
  timestamp_format: Timestamp_format,
  timestamp_ltz: Timestamp_ltz,
  timestamp_ntz: Timestamp_ntz,
  timestamp_tz: Timestamp_tz,
  timestampltz: Timestampltz,
  timestampntz: Timestampntz,
  timestamptz: Timestamptz,
  to: To,
  top: Top,
  triggers: Triggers,
  trim_space: Trim_space,
  true: True,
  truncate: Truncate,
  truncatecolumns: Truncatecolumns,
  try_cast: Try_cast,
  ts: Ts,
  undbounded: Unbounded,
  union: Union,
  unique: Unique,
  unpivot: Unpivot,
  update: Update,
  usage: Usage,
  use: Use,
  using: Using,
  utf8: Utf8,
  validate_utf8: Validate_utf8,
  validate: Validate,
  values: Values,
  values: Values,
  varbinary: Varbinary,
  varchar: Varchar,
  varying: Varying,
  volatile: Volatile,
  weekly: Weekly,
  when: When,
  where: Where,
  with: With,
  without: Without,
  xml: Xml,
  yearly: Yearly,
  zone: Zone,
  zstd: Zstd
};

export const specializeIdentifier = (value, stack) => {
  return keywordTokens[value.toLowerCase()] || -1;
};

const contextualKeywordTokens = {
  account: Account,
  action: Action,
  alter: Alter,
  application: Application,
  azure: Azure,
  channel: Channel,
  columns: Columns,
  comment: Comment,
  commit: Commit,
  d: D,
  data: Data,
  database: Database,
  day: Day,
  default_ddl_collation: Default_ddl_collation,
  email: Email,
  enabled: Enabled,
  first_name: First_name,
  gcs: Gcs,
  hour: Hour,
  identity: Identity,
  ilike: Ilike,
  input: Input,
  integration: Integration,
  key: Key,
  last_name: Last_name,
  left: Left,
  materialized: Materialized,
  minute: Minute,
  month: Month,
  must_change_password: Must_change_password,
  null: Null,
  order: Order,
  organization: Organization,
  owner: Owner,
  percent: Percent,
  policies: Policies,
  policy: Policy,
  regexp: Regexp,
  region: Region,
  resume: Resume,
  role: Role,
  schema: Schema,
  secure: Secure,
  security: Security,
  stage: Stage,
  tag: Tag,
  text: Text,
  timestamp: Timestamp,
  transient: Transient,
  type: Type,
  url: Url,
  user: User,
  view: View,
  views: Views,
  warehouse: Warehouse,
  x: X,
  year: Year
};

export const extendIdentifier = (value, stack) => {
  return contextualKeywordTokens[value.toLowerCase()] || -1;
};
