import {
  Aad_provisioner,
  Use,
  Grant,
  Attach,
  To,
  Privileges,
  Lateral,
  Activate,
  Seed,
  Rows,
  Repeatable,
  Alter,
  Delete,
  Import,
  Insert,
  Manage,
  Modify,
  Unbounded,
  Preceding,
  Following,
  Range,
  Asc,
  Nulls,
  Year,
  Month,
  Day,
  Hour,
  Minute,
  Then,
  Second, 
  D,
  T,
  Ts,
  Fn,
  Extract,
  Position,
  Override,
  Ownership,
  Operate,
  Pacwrite,
  Pacread,
  Setup,
  Update,
  Rebuild,
  Reference,
  Usage,
  Read,
  Write,
  Apply,
  Any,
  Exchange,
  Listing,
  Profile,
  Execution,
  Stream,
  Replication,
  Keys,
  Restrictions,
  System,
  Support,
  Volume,
  Organization,
  Parameters,
  Release,
  Optimization,
  Credential,
  Application,
  Tag,
  Gscluster,
  Databases,
  Formats,
  Functions,
  Integrations,
  Procedures,
  Stages,
  Scheams,
  Sequences,
  Tables,
  Pipes,
  Streams,
  Tasks,
  Users,
  Views,
  Volumes,
  Warehouses,
  Rely, 
  Norely, 
  Enforced,
  Objects,
  Action,
  Get,
  Immediate,
  Monitors,
  Networks,
  Applications,
  Policies,
  Future,
  Option,
  Revoke,
  Current,
  Imported,
  Session,
  Union,
  Except,
  Abort_detached_query,
  Abort_statement,
  Access,
  Account,
  Admin,
  Admin_name,
  Admin_password,
  After,
  Allow_duplicate,
  Allow_overlapping_execution,
  Allowed_IP_List,
  And,
  Api,
  Rollback,
  Text,
  Api_allowed_prefixes,
  Api_aws_role_arn,
  Api_blocked_prefixes,
  Api_integration,
  Api_key,
  Block,
  Bernoulli,
  Api_provider,
  As,
  At,
  Auto,
  Auto_ingest,
  Auto_refresh,
  Auto_refresh_materialized_views_on_secondary,
  Auto_resume,
  Auto_suspend,
  Autocommit,
  Deferrable,
  Initiallly,
  Deferred,
  Autoincrement,
  Avro,
  Aws_api_gateway,
  Aws_cse,
  Aws_key_id,
  Aws_private_api_gateway,
  Aws_role,
  Aws_secret_key,
  Aws_sns_topic,
  Aws_sse_kms,
  Aws_sse_s3,
  Aws_token,
  Azure,
  Azure_ad_application_id,
  Azure_api_management,
  Azure_cse,
  Azure_sas_token,
  Azure_storage_queue,
  Azure_storage_queue_primary_uri,
  Azure_tenant_id,
  Base64,
  Before,
  Between,

  Binary_as_text,
  Binary_format,
  Binary_input_format,
  Binary_output_format,
  Blob,
  Blocked_IP_List,
  Blocked_roles_list,
  Bool,
  Boolean,
  Brotli,
  Business,
  Business_critical,
  By,
  Bz2,
  Called,
  Caller,
  Cascade,
  Case_insensitive,
  Case_sensitive,
  Change,
  Change_tracking,
  Clone,
  Cluster,
  Collate,
  Columns,
  Comment,
  Compression,
  Confidential,
  Constraint,
  Context_headers,
  Continue,
  Copy,
  Copy_options,
  Channel,
  Copyoptions,
  Core,
  Connect_by_root,
  Create,
  Credentials,
  Credit_quota,
  Critical,
  Cron,
  Csv,
  Custom,
  Commit,
  Daily,
  Over,
  Data,
  Data_retention_time_in_days,
  Database,
  Date_format,
  X,
  Date_input_format,
  Date_output_format,
  Days_to_expiry,
  Default,
  Else,
  Default_ddl_collation,
  Default_namespace,
  Default_role,
  Default_warehouse,
  Deflate,
  Desc,
  Describe,
  Disable,
  Disable_auto_convert,
  Validate,
  Disable_snowflake_data,
  Disabled,
  Display_name,
  Do,
  Drop,
  Economy,
  Edition,
  Email,
  Email_address,
  Empty_field_as_null,
  Enable,
  Enable_for_privilege,
  Enable_octal,
  Enabled,
  Encoding,
  Encryption,
  End_timestamp,
  Enforce_length,
  Enterprise,
  Error_on_column_count_mismatch,
  Error_on_nondeterministic_merge,
  Error_on_nondeterministic_update,
  Escape,
  Escape_unenclosed_field,
  Execute,
  Exists,
  External,
  External_oauth,
  External_oauth_any_role_mode,
  External_oauth_audience_list,
  External_oauth_issuer,
  External_oauth_jws_keys_url,
  External_oauth_rsa_public_key,
  External_oauth_rsa_public_key_2,
  External_oauth_snowflake_user_mapping_attribute,
  External_oauth_token_user_mapping_claim,
  External_oauth_type,
  Externalstage,
  False,
  Field_delimiter,
  Field_optionally_enclosed_by,
  File,
  File_extension,
  File_format,
  First,
  First_name,
  For,
  Force,
  Foreign,
  Format,
  Format_name,
  Formattypeoptions,
  Frequency,
  From,
  Function,
  Gcp_pubsub,
  Novalidate,
  Match,
  Show,
  Full, 
  Partial,
  Simple,
  Gcp_pubsub_subscription_name,
  Gcs,
  Gcs_sse_kms,
  Generic_scim_provisioner,
  Global,
  Google_api_gateway,
  Google_audience,
  Grants,
  GroupLeft,
  GroupRight,
  Gzip,
  Schemas,
  Headers,
  Truncate,
  Search,
  Oj,
  Index,
  Hex,
  IP,
  Identity,
  If,
  Ignore_utf8_errors,
  Ignoring,
  Immediately,
  History,
  Limit,
  Immutable,
  Having,
  Qualify,
  In,
  Increment,
  Initially_suspended,
  Input,
  Integration,
  Is,
  Json,
  Json_indent,
  Key,
  Kms_key_id,
  Language,
  Large,
  Last,
  Last_name,

  Like,
  List,
  Local,
  Location,
  Lock_timeout,
  Login_name,
  Lzo,
  Managed,
  Masking,
  Master_key,
  Match_by_column_name,
  Materialized,
  Max_batch_rows,
  Max_cluster_count,
  Max_concurrency_level,
  Max_data_extension_time_in_days,
  Medium,
  Middle_name,
  Min_cluster_count,
  Connect,
  Mins_to_bypass_mfa,
  Mins_to_unlock,
  Fetch,
  Next,
  Case,
  Cast,
  Monitor,
  Monthly,
  Set,
  Intersect,
  Must,
  No,
  Must_change_password,
  Name,
  Net,
  Network,
  Join,
  Inner,
  Left,
  Outer,
  Right, 
  Sample, 
  Tablesample,
  Semi,
  Network_policy,
  Never,
  None,
  Not,
  Notification,
  Notification_provider,
  Notify,
  Null,
  Null_if,
  Numeric,
  Oauth,
  Oauth_allow_non_tls_redirect_uri,
  Oauth_client,
  Oauth_client_rsa_public_key,
  Oauth_client_rsa_public_key_2,
  Oauth_client_type,
  Oauth_enforce_pkce,
  Oauth_issue_refresh_tokens,
  Oauth_redirect_uri,
  Oauth_refresh_token_validity,
  Of,
  Offset,
  Okta,
  Okta_provisioner,
  On,
  On_error,
  Only,
  Or,
  Orc,
  Owner,
  Parquet,
  Partition,
  Password,
  Pattern,
  Percent,
  Ping_federate,
  Pipe,
  Policy,
  Pre_authorized_roles_list,
  Preserve_space,
  Primary,
  Procedure,
  Public,
  Purge,
  Query_tag,
  Queue,
  Raw_deflate,
  Cross,
  Reader,
  Record_delimiter,
  Recursive,
  Distinct,
  Top,
  References,
  Refresh_on_create,
  Natural,
  Region,
  Region_group,
  Replace,
  Replace_invalid_characters,
  Replica,
  Resource,
  Resource_monitor,
  Restrict,
  Return_failed_only,
  Order,
  Values,
  Returns,
  Ribe,
  Role,
  Row,
  Rows_per_resultset,
  Rsa_public_key,
  Rsa_public_key_2,
  Run_as_role,
  S3,
  Saml2,
  Saml2_enable_sp_initiated,
  Saml2_force_authn,
  Saml2_issuer,
  Saml2_post_logout_redirect_url,
  Saml2_provider,
  Saml2_requested_nameid_format,
  Saml2_sign_request,
  Saml2_snowflake_acs_url,
  Saml2_snowflake_issuer_url,
  Saml2_snowflake_x509_cert,
  Saml2_sp_initiated_login_page_label,
  Saml2_sso_url,
  Saml2_x509_cert,
  Scaling_policy,
  Schedule,
  Schema,
  Scim,
  Scim_client,
  Secure,
  Security,
  Select,
  Unpivot,
  Sequence,
  Share,
  Simulated_data_sharing_consumer,
  Size_limit,
  Skip_blank_lines,
  Skip_byte_order_mark,
  Skip_file,
  Skip_header,
  Small,
  Snappy,
  Snappy_compression,
  Snowflake_support,
  Stage,
  Stage_copy_options,
  Stage_file_format,
  Standard,
  Start,
  Start_timestamp,
  Statement,
  Statement_queued_timeout_in_seconds,
  Statement_timeout_in_seconds,
  Storage,
  Storage_integration,
  Strict,
  Strict_json_output,
  Strip_null_values,
  Strip_outer_array,
  Strip_outer_element,
  Supported,
  Suspend,
  Suspend_immediate,
  Group,
  Grouping,
  Sets,
  Cube,
  Rollup,
  Table,
  Task,
  Temp,
  Template,
  Temporary,
  Time_format,
  Time_input_format,
  Time_output_format,
  Timestamp,
  Timestamp_day_is_always_24h,
  Timestamp_format,
  Timestamp_input_format,
  Timestamp_ltz_output_format,
  Timestamp_ntz_output_format,
  Timestamp_output_format,
  Timestamp_type_mapping,
  Timestamp_tz_output_format,
  Timezone,
  Transaction_default_isolation_level,
  Transient,
  Triggers,
  Trim_space,
  True,
  Div,
  Truncatecolumns,
  Try_cast,
  Two_digit_century_start,
  Type,
  Unique,
  Prior,
  Unsupported_ddl_action,
  Url,
  Use_cached_result,
  User,
  User_task_timeout_ms,
  Terse,
  Starts,
  Using,
  Utf8,
  Validate_utf8,
  View,
  Volatile,
  Warehouse,
  Warehouse_size,
  Week_of_year_policy,
  Week_start,
  Weekly,
  When,
  Where,
  Windows,
  With,
  X4large,
  Xlarge,
  Xml,
  Xsmall,
  Xxlarge,
  Xxxlarge,
  Yearly,
  Zstd,
  End,
  Work,
  All,
  Overwrite,
  Into,
  Comma,
  Regexp,
  Ilike,
  Precision,
  Varying,
  Varchar,
  Character,
  Char,
  String,
  Binary,
  Varbinary,
  Decimal,
  Dec,
  Number,
  Timestampltz,
  Timestamp_ltz,
  Zone,
  Timestampntz,
  Timestamp_ntz,
  Without,
  Datetime,
  Timestamptz,
  Timestamp_tz


} from "./parser.terms.js";

const keywordTokens = {
  aad_provisioner: Aad_provisioner,
  abort_detached_query: Abort_detached_query,
  //abort_statement: Abort_statement,
  access: Access,
  account: Account,
  admin: Admin,
  admin_name: Admin_name,
  admin_password: Admin_password,
  after: After,
  allow_duplicate: Allow_duplicate,
  allow_overlapping_execution: Allow_overlapping_execution,
  allowed_ip_list: Allowed_IP_List,
  and: And,
  api: Api,
  api_allowed_prefixes: Api_allowed_prefixes,
  api_aws_role_arn: Api_aws_role_arn,
  api_blocked_prefixes: Api_blocked_prefixes,
  api_integration: Api_integration,
  api_key: Api_key,
  api_provider: Api_provider,
  as: As,
  at: At,
  auto: Auto,
  auto_ingest: Auto_ingest,
  work: Work,
  auto_refresh: Auto_refresh,
  auto_refresh_materialized_views_on_secondary:
  Auto_refresh_materialized_views_on_secondary,
  rollback : Rollback,
  truncate : Truncate,
  auto_resume: Auto_resume,
  auto_suspend: Auto_suspend,
  autocommit: Autocommit,
  autoincrement: Autoincrement,
  avro: Avro,
  aws_api_gateway: Aws_api_gateway,
  aws_cse: Aws_cse,
  aws_key_id: Aws_key_id,
  aws_private_api_gateway: Aws_private_api_gateway,
  aws_role: Aws_role,
  aws_secret_key: Aws_secret_key,
  aws_sse_kms: Aws_sse_kms,
  aws_sse_s3: Aws_sse_s3,
  aws_token: Aws_token,
  union : Union,
  intersect : Intersect,
  azure_ad_application_id: Azure_ad_application_id,
  azure_api_management: Azure_api_management,
  azure_cse: Azure_cse,
  azure_sas_token: Azure_sas_token,
  azure_storage_queue: Azure_storage_queue,
  azure_storage_queue_primary_uri: Azure_storage_queue_primary_uri,
  azure_tenant_id: Azure_tenant_id,
  base64: Base64,
  before: Before,
  between: Between,
  binary_as_text: Binary_as_text,
  binary_format: Binary_format,
  binary_input_format: Binary_input_format,
  binary_output_format: Binary_output_format,
  blob: Blob,
  no : No,
  overwrite : Overwrite,
  values : Values,
  x : X,
  blocked_ip_list: Blocked_IP_List,
  blocked_roles_list: Blocked_roles_list,
  bool: Bool,
  boolean: Boolean,
  brotli: Brotli,
  business: Business,
  business_critical: Business_critical,
  by: By,
  bz2: Bz2,
  commit : Commit,
  group : Group,
  comma : Comma,
  connect : Connect,
  try_cast : Try_cast,
  undbounded : Unbounded,
  Preceding : Preceding,
  following : Following,
  range : Range,
  asc : Asc,
  nulls : Nulls,
  year : Year,
  month : Month,
  day : Day,
  hour : Hour,
  minute : Minute,
  second : Second,
  grouping : Grouping,
  sets : Sets,
  cube : Cube,
  rollup :Rollup,
  called: Called,
  caller: Caller,
  lateral : Lateral,
  unpivot : Unpivot,
  cascade: Cascade,
  case_insensitive: Case_insensitive,
  case_sensitive: Case_sensitive,
  connect_by_root : Connect_by_root,
  change: Change,
  change_tracking: Change_tracking,
  clone: Clone,
  cluster: Cluster,
  collate: Collate,
  columns: Columns,
  case : Case,
  cast : Cast,
  over : Over,
  comment: Comment,
  compression: Compression,
  confidential: Confidential,
  constraint: Constraint,
  context_headers: Context_headers,
  continue: Continue,
  copy: Copy,
  copy_options: Copy_options,
  copyoptions: Copyoptions,
  core: Core,
  create: Create,
  credentials: Credentials,
  credit_quota: Credit_quota,
  critical: Critical,
  cron: Cron,
  prior : Prior,
  csv: Csv,
  custom: Custom,
  daily: Daily,
  data_retention_time_in_days: Data_retention_time_in_days,
  database: Database,
  sample : Sample, 
  bernoulii : Bernoulli, 
  block : Block,
  tablesample : Tablesample,
  date_format: Date_format,
  date_input_format: Date_input_format,
  date_output_format: Date_output_format,
  days_to_expiry: Days_to_expiry,
  default: Default,
  default_ddl_collation: Default_ddl_collation,
  default_namespace: Default_namespace,
  default_role: Default_role,
  default_warehouse: Default_warehouse,
  deflate: Deflate,
  desc: Desc,
  describe: Describe,
  disable: Disable,
  disable_auto_convert: Disable_auto_convert,
  disable_snowflake_data: Disable_snowflake_data,
  disabled: Disabled,
  display_name: Display_name,
  rely : Rely,
  norely : Norely,
  enforced : Enforced,
  get: Get,
  deferrable : Deferrable,
  initiallly : Initiallly,
  do: Do,
  grant: Grant,
  to: To,
  privileges: Privileges,
  activate: Activate,
  alter: Alter,
  delete: Delete,
  import: Import,
  insert: Insert,
  manage: Manage,
  starts : Starts,
  limit : Limit,
  history : History,
  div : Div,
  modify: Modify,
  override: Override,
  ownership: Ownership,
  operate: Operate,
  repeatable : Repeatable,
  natural : Natural,
  immediate : Immediate,
  pacwrite: Pacwrite,
  pacread: Pacread,
  setup: Setup,
  update: Update,
  rebuild: Rebuild,
  reference: Reference,
  usage: Usage,
  read: Read,
  write: Write,
  apply: Apply,
  any: Any,
  exchange: Exchange,
  listing: Listing,
  profile: Profile,
  oj : Oj,
  then : Then,
  join : Join,
  inner : Inner,
  left : Left,
  outer : Outer,
  right : Right, 
  full : Full,
  semi : Semi,
  execution: Execution,
  stream: Stream,
  replication: Replication,
  fetch : Fetch,
  next : Next,
  keys: Keys,
  restrictions: Restrictions,
  system: System,
  support: Support,
  volume: Volume,
  Deferred : Deferred,
  immediate : Immediate,
  novalidate : Novalidate,
  validate : Validate,
  organization: Organization,
  parameters: Parameters,
  release: Release,
  optimization: Optimization,
  credential: Credential,
  application: Application,
  gscluster: Gscluster,
  databases: Databases,
  formats: Formats,
  functions: Functions,
  integrations: Integrations,
  procedures: Procedures,
  stages: Stages,
  scheams: Scheams,
  sequences: Sequences,
  tables: Tables,
  pipes: Pipes,
  streams: Streams,
  tasks: Tasks,
  users: Users,
  views: Views,
  volumes: Volumes,
  warehouses: Warehouses,
  objects: Objects,
  monitors: Monitors,
  networks: Networks,
  applications: Applications,
  policies: Policies,
  future: Future,
  option: Option,
  revoke: Revoke,
  current: Current,
  imported: Imported,
  restrictions: Restrictions,
  drop: Drop,
  economy: Economy,
  edition: Edition,
  email: Email,
  email_address: Email_address,
  empty_field_as_null: Empty_field_as_null,
  enable: Enable,
  all : All,
  enable_for_privilege: Enable_for_privilege,
  enable_octal: Enable_octal,
  encoding: Encoding,
  d : D,
  t : T,
  ts : Ts,
  fn : Fn,
  extact : Extract,
  position : Position,
  encryption: Encryption,
  end_timestamp: End_timestamp,
  enforce_length: Enforce_length,
  enterprise: Enterprise,
  error_on_column_count_mismatch: Error_on_column_count_mismatch,
  error_on_nondeterministic_merge: Error_on_nondeterministic_merge,
  error_on_nondeterministic_update: Error_on_nondeterministic_update,
  escape: Escape,
  escape_unenclosed_field: Escape_unenclosed_field,
  execute: Execute,
  exists: Exists,
  external: External,
  distinct : Distinct,
  match :Match, 
  partial : Partial, 
  simple : Simple,
  set : Set,
  external_oauth: External_oauth,
  external_oauth_any_role_mode: External_oauth_any_role_mode,
  external_oauth_audience_list: External_oauth_audience_list,
  external_oauth_issuer: External_oauth_issuer,
  external_oauth_jws_keys_url: External_oauth_jws_keys_url,
  external_oauth_rsa_public_key: External_oauth_rsa_public_key,
  external_oauth_rsa_public_key_2: External_oauth_rsa_public_key_2,
  external_oauth_snowflake_user_mapping_attribute:
    External_oauth_snowflake_user_mapping_attribute,
  external_oauth_token_user_mapping_claim:
    External_oauth_token_user_mapping_claim,
  external_oauth_type: External_oauth_type,
  externalstage: Externalstage,
  false: False,
  field_delimiter: Field_delimiter,
  field_optionally_enclosed_by: Field_optionally_enclosed_by,
  file: File,
  file_extension: File_extension,
  file_format: File_format,
  first: First,
  first_name: First_name,
  for: For,
  force: Force,
  foreign: Foreign,
  format: Format,
  format_name: Format_name,
  formattypeoptions: Formattypeoptions,
  cross : Cross,
  group : Group,
  order : Order,
  frequency: Frequency,
  attach : Attach,
  schemas : Schemas,
  from: From,
  function: Function,
  gcp_pubsub: Gcp_pubsub,
  gcp_pubsub_subscription_name: Gcp_pubsub_subscription_name,
  except: Except,
  show : Show,
  terse : Terse,
  gcs_sse_kms: Gcs_sse_kms,
  generic_scim_provisioner: Generic_scim_provisioner,
  global: Global,
  google_api_gateway: Google_api_gateway,
  google_audience: Google_audience,
  grants: Grants,
  groupleft: GroupLeft,
  groupright: GroupRight,
  gzip: Gzip,
  headers: Headers,
  hex: Hex,
  ip: IP,
  identity: Identity,
  if: If,
  ignore_utf8_errors: Ignore_utf8_errors,
  ignoring: Ignoring,
  immediately: Immediately,
  immutable: Immutable,
  in: In,
  increment: Increment,
  initially_suspended: Initially_suspended,
  is: Is,
  json: Json,
  json_indent: Json_indent,
  key: Key,
  kms_key_id: Kms_key_id,
  language: Language,
  large: Large,
  last: Last,
  last_name: Last_name,
  like: Like,
  list: List,
  local: Local,
  session : Session,
  location: Location,
  lock_timeout: Lock_timeout,
  login_name: Login_name,
  search : Search,
  index : Index,
  lzo: Lzo,
  values : Values,
  managed: Managed,
  masking: Masking,
  master_key: Master_key,
  match_by_column_name: Match_by_column_name,
  materialized: Materialized,
  max_batch_rows: Max_batch_rows,
  max_cluster_count: Max_cluster_count,
  max_concurrency_level: Max_concurrency_level,
  max_data_extension_time_in_days: Max_data_extension_time_in_days,
  medium: Medium,
  middle_name: Middle_name,
  min_cluster_count: Min_cluster_count,
  mins_to_bypass_mfa: Mins_to_bypass_mfa,
  mins_to_unlock: Mins_to_unlock,
  monitor: Monitor,
  monthly: Monthly,
  must: Must,
  must_change_password: Must_change_password,
  net: Net,
  network: Network,
  network_policy: Network_policy,
  never: Never,
  use : Use,
  none: None,
  not: Not,
  notification: Notification,
  notification_provider: Notification_provider,
  notify: Notify,
  null_if: Null_if,
  numeric: Numeric,
  oauth: Oauth,
  oauth_allow_non_tls_redirect_uri: Oauth_allow_non_tls_redirect_uri,
  oauth_client: Oauth_client,
  oauth_client_rsa_public_key: Oauth_client_rsa_public_key,
  oauth_client_rsa_public_key_2: Oauth_client_rsa_public_key_2,
  oauth_client_type: Oauth_client_type,
  oauth_enforce_pkce: Oauth_enforce_pkce,
  oauth_issue_refresh_tokens: Oauth_issue_refresh_tokens,
  oauth_redirect_uri: Oauth_redirect_uri,
  oauth_refresh_token_validity: Oauth_refresh_token_validity,
  of: Of,
  offset: Offset,
  rows : Rows,
  seed : Seed,
  okta: Okta,
  okta_provisioner: Okta_provisioner,
  on: On,
  top: Top,
  on_error: On_error,
  only: Only,
  or: Or,
  orc: Orc,
  owner: Owner,
  parquet: Parquet,
  partition: Partition,
  password: Password,
  pattern: Pattern,
  percent: Percent,
  ping_federate: Ping_federate,
  pipe: Pipe,
  policy: Policy,
  pre_authorized_roles_list: Pre_authorized_roles_list,
  preserve_space: Preserve_space,
  primary: Primary,
  procedure: Procedure,
  purge: Purge,
  query_tag: Query_tag,
  queue: Queue,
  raw_deflate: Raw_deflate,
  reader: Reader,
  record_delimiter: Record_delimiter,
  recursive: Recursive,
  references: References,
  refresh_on_create: Refresh_on_create,
  region: Region,
  region_group: Region_group,
  replace: Replace,
  replace_invalid_characters: Replace_invalid_characters,
  replica: Replica,
  resource: Resource,
  resource_monitor: Resource_monitor,
  restrict: Restrict,
  return_failed_only: Return_failed_only,
  returns: Returns,
  ribe: Ribe,
  role: Role,
  row: Row,
  rows_per_resultset: Rows_per_resultset,
  rsa_public_key: Rsa_public_key,
  rsa_public_key_2: Rsa_public_key_2,
  run_as_role: Run_as_role,
  s3: S3,
  saml2: Saml2,
  saml2_enable_sp_initiated: Saml2_enable_sp_initiated,
  saml2_force_authn: Saml2_force_authn,
  saml2_issuer: Saml2_issuer,
  saml2_post_logout_redirect_url: Saml2_post_logout_redirect_url,
  saml2_provider: Saml2_provider,
  saml2_requested_nameid_format: Saml2_requested_nameid_format,
  saml2_sign_request: Saml2_sign_request,
  saml2_snowflake_acs_url: Saml2_snowflake_acs_url,
  saml2_snowflake_issuer_url: Saml2_snowflake_issuer_url,
  saml2_snowflake_x509_cert: Saml2_snowflake_x509_cert,
  saml2_sp_initiated_login_page_label: Saml2_sp_initiated_login_page_label,
  saml2_sso_url: Saml2_sso_url,
  saml2_x509_cert: Saml2_x509_cert,
  scaling_policy: Scaling_policy,
  schema: Schema,
  scim: Scim,
  else : Else,
  having : Having,
  qualify : Qualify,
  scim_client: Scim_client,
  security: Security,
  select: Select,
  sequence: Sequence,
  share: Share,
  simulated_data_sharing_consumer: Simulated_data_sharing_consumer,
  size_limit: Size_limit,
  skip_blank_lines: Skip_blank_lines,
  skip_byte_order_mark: Skip_byte_order_mark,
  skip_file: Skip_file,
  skip_header: Skip_header,
  small: Small,
  snappy: Snappy,
  snappy_compression: Snappy_compression,
  snowflake_support: Snowflake_support,
  stage: Stage,
  stage_copy_options: Stage_copy_options,
  stage_file_format: Stage_file_format,
  standard: Standard,
  start: Start,
  start_timestamp: Start_timestamp,
  statement: Statement,
  statement_queued_timeout_in_seconds: Statement_queued_timeout_in_seconds,
  statement_timeout_in_seconds: Statement_timeout_in_seconds,
  storage: Storage,
  storage_integration: Storage_integration,
  strict: Strict,
  strict_json_output: Strict_json_output,
  strip_null_values: Strip_null_values,
  strip_outer_array: Strip_outer_array,
  strip_outer_element: Strip_outer_element,
  supported: Supported,
  suspend: Suspend,
  suspend_immediate: Suspend_immediate,
  table: Table,
  task: Task,
  template: Template,
  temp: Temp,
  temporary: Temporary,
  text: Text,
  time_format: Time_format,
  time_input_format: Time_input_format,
  time_output_format: Time_output_format,
  timestamp: Timestamp,
  timestamp_day_is_always_24h: Timestamp_day_is_always_24h,
  timestamp_format: Timestamp_format,
  timestamp_input_format: Timestamp_input_format,
  timestamp_ltz_output_format: Timestamp_ltz_output_format,
  timestamp_ntz_output_format: Timestamp_ntz_output_format,
  timestamp_output_format: Timestamp_output_format,
  timestamp_type_mapping: Timestamp_type_mapping,
  timestamp_tz_output_format: Timestamp_tz_output_format,
  timezone: Timezone,
  transaction_default_isolation_level: Transaction_default_isolation_level,
  transient: Transient,
  triggers: Triggers,
  trim_space: Trim_space,
  true: True,
  truncatecolumns: Truncatecolumns,
  two_digit_century_start: Two_digit_century_start,
  unique: Unique,
  unsupported_ddl_action: Unsupported_ddl_action,
  use_cached_result: Use_cached_result,
  user: User,
  user_task_timeout_ms: User_task_timeout_ms,
  using: Using,
  utf8: Utf8,
  validate_utf8: Validate_utf8,
  view: View,
  volatile: Volatile,
  warehouse: Warehouse,
  warehouse_size: Warehouse_size,
  week_of_year_policy: Week_of_year_policy,
  week_start: Week_start,
  weekly: Weekly,
  when: When,
  where: Where,
  windows: Windows,
  with: With,
  x4large: X4large,
  xlarge: Xlarge,
  xml: Xml,
  xsmall: Xsmall,
  xxlarge: Xxlarge,
  xxxlarge: Xxxlarge,
  yearly: Yearly,
  zstd: Zstd,
  end : End,
  into : Into,
  precsion : Precision,
  varying : Varying,
  varchar : Varchar,
  character : Character,
  char : Char,
  string : String,
  binary : Binary,
  varbinary :Varbinary,
  decimal : Decimal,
  dec : Dec,
  number : Number,
  timestampltz : Timestampltz,
  timestamp_ltz : Timestamp_ltz,
  zone : Zone,
  timestampntz : Timestampntz,
  timestamp_ntz : Timestamp_ntz,
  without : Without,
  datetieme : Datetime,
  timestamptz : Timestamptz,
  timestamp_tz : Timestamp_tz

};

export const specializeIdentifier = (value, stack) => {
  return keywordTokens[value.toLowerCase()] || -1;
};


const contextualKeywordTokens = {

  action : Action,
  integration: Integration,
  aws_sns_topic : Aws_sns_topic,
  null: Null,
  url : Url,
  regexp : Regexp,
  ilike : Ilike,
  tag: Tag,
  name : Name,
  input : Input,
  type: Type,
  channel : Channel,
  enabled: Enabled,
  gcs: Gcs,
  azure: Azure,
  text : Text,
  secure: Secure,
  data: Data,
  public: Public,
  schedule: Schedule


}

export const extendIdentifier = (value, stack) => {
  return contextualKeywordTokens[value.toLowerCase()] || -1;
}