import {
  Access,
  Account,
  Action,
  Activate,
  Admin_name,
  Admin_password,
  Admin,
  After,
  All,
  Allow_duplicate,
  Allowed_IP_List,
  Alter,
  And,
  Any,
  Api_allowed_prefixes,
  Api_aws_role_arn,
  Api_blocked_prefixes,
  Api_integration,
  Api_key,
  Api_provider,
  Api,
  Application,
  Applications,
  Apply,
  As,
  Asc,
  At,
  Attach,
  Auto_ingest,
  Auto_refresh_materialized_views_on_secondary,
  Auto_refresh,
  Auto_resume,
  Auto_suspend,
  Auto,
  Autocommit,
  Autoincrement,
  Avro,
  Aws_api_gateway,
  Aws_cse,
  Aws_key_id,
  Aws_private_api_gateway,
  Aws_role,
  Aws_secret_key,
  Aws_sns_topic,
  Aws_sse_kms,
  Aws_sse_s3,
  Aws_token,
  Azure_ad_application_id,
  Azure_api_management,
  Azure_cse,
  Azure_sas_token,
  Azure_storage_queue_primary_uri,
  Azure_storage_queue,
  Azure_tenant_id,
  Azure,
  Base64,
  Before,
  Bernoulli,
  Between,
  Binary_as_text,
  Binary_format,
  Binary_input_format,
  Binary_output_format,
  Binary,
  Blob,
  Block,
  Blocked_IP_List,
  Blocked_roles_list,
  Bool,
  Boolean,
  Brotli,
  Business_critical,
  Business,
  By,
  Bz2,
  Call,
  Called,
  Caller,
  Cascade,
  Case_insensitive,
  Case_sensitive,
  Case,
  Cast,
  Change_tracking,
  Change,
  Channel,
  Char,
  Character,
  Clone,
  Cluster,
  Collate,
  Columns,
  Comment,
  Commit,
  Compression,
  Confidential,
  Connect_by_root,
  Connect,
  Connection,
  Constraint,
  Context_headers,
  Continue,
  Copy_options,
  Copy,
  Copyoptions,
  Core,
  Create,
  Credential,
  Credentials,
  Credit_quota,
  Critical,
  Cron,
  Cross,
  Csv,
  Cube,
  Current,
  Custom,
  D,
  Daily,
  Data_retention_time_in_days,
  Data,
  Database,
  Databases,
  Date_format,
  Datetime,
  Day,
  Days_to_expiry,
  Dec,
  Decimal,
  Default_ddl_collation,
  Default_namespace,
  Default_role,
  Default_warehouse,
  Default,
  Deferrable,
  Deferred,
  Deflate,
  Delete,
  Desc,
  Describe,
  Disable_auto_convert,
  Disable_snowflake_data,
  Disable,
  Disabled,
  Display_name,
  Distinct,
  Div,
  Do,
  Drop,
  Economy,
  Edition,
  Else,
  Email_address,
  Email,
  Empty_field_as_null,
  Enable_for_privilege,
  Enable_octal,
  Enable,
  Enabled,
  Encoding,
  Encryption,
  End_timestamp,
  End,
  Endset,
  Enforce_length,
  Enforced,
  Enterprise,
  Error_on_column_count_mismatch,
  Escape_unenclosed_field,
  Escape,
  Except,
  Exchange,
  Execute,
  Execution,
  Exists,
  External,
  Extract,
  False,
  Fetch,
  Field_delimiter,
  Field_optionally_enclosed_by,
  File_extension,
  File_format,
  File,
  First_name,
  First,
  Fn,
  Following,
  For,
  Force,
  Foreign,
  Format_name,
  Format,
  Formats,
  Formattypeoptions,
  Frequency,
  From,
  Full,
  Function,
  Functions,
  Future,
  Gcs_sse_kms,
  Gcs,
  Generic_scim_provisioner,
  Get,
  Global,
  Google_api_gateway,
  Google_audience,
  Grant,
  Grants,
  Group,
  Grouping,
  Gscluster,
  Gzip,
  Having,
  Headers,
  Hex,
  History,
  Hour,
  Identity,
  If,
  Ignore_utf8_errors,
  Ignoring,
  Ilike,
  Immediate,
  Immediately,
  Immutable,
  Import,
  Imported,
  In,
  Increment,
  Index,
  Initiallly,
  Initially_suspended,
  Inner,
  Input,
  Insert,
  Integration,
  Integrations,
  Intersect,
  Into,
  Ip,
  Is,
  Join,
  Json_indent,
  Json,
  Key,
  Keys,
  Kms_key_id,
  Language,
  Large,
  Last_name,
  Last,
  Lateral,
  Left,
  Like,
  Limit,
  List,
  Listing,
  Local,
  Location,
  Lock_timeout,
  Login_name,
  Lzo,
  Manage,
  Managed,
  Masking,
  Master_key,
  Match_by_column_name,
  Match,
  Materialized,
  Max_batch_rows,
  Max_cluster_count,
  Max_concurrency_level,
  Max_data_extension_time_in_days,
  Medium,
  Middle_name,
  Min_cluster_count,
  Mins_to_bypass_mfa,
  Mins_to_unlock,
  Minute,
  Modify,
  Monitor,
  Monitors,
  Month,
  Monthly,
  Must_change_password,
  Must,
  Name,
  Natural,
  Net,
  Network_policy,
  Network,
  Networks,
  Never,
  Next,
  No,
  None,
  Norely,
  Not,
  Notification_provider,
  Notification,
  Notify,
  Novalidate,
  Null_if,
  Null,
  Nulls,
  Number,
  Numeric,
  Objects,
  Of,
  Offset,
  Oj,
  Okta,
  On_error,
  On,
  Only,
  Operate,
  Optimization,
  Option,
  Or,
  Orc,
  Order,
  Organization,
  Outer,
  Over,
  Override,
  Overwrite,
  Owner,
  Ownership,
  Pacread,
  Pacwrite,
  Parameters,
  Parquet,
  Partial,
  Partition,
  Password,
  Pattern,
  Percent,
  Pipe,
  Pipes,
  Policies,
  Policy,
  Position,
  Pre_authorized_roles_list,
  Preceding,
  Precision,
  Preserve_space,
  Primary,
  Prior,
  Privileges,
  Procedure,
  Procedures,
  Profile,
  Public,
  Purge,
  Qualify,
  Query_tag,
  Queue,
  Range,
  Raw_deflate,
  Read,
  Reader,
  Rebuild,
  Record_delimiter,
  Recursive,
  Reference,
  References,
  Refresh_on_create,
  Regexp,
  Region_group,
  Region,
  Release,
  Rely,
  Repeatable,
  Replace_invalid_characters,
  Replace,
  Replica,
  Replication,
  Resource_monitor,
  Resource,
  Restrict,
  Restrictions,
  Resume,
  Return_failed_only,
  Returns,
  Revoke,
  Ribe,
  Right,
  Role,
  Rollback,
  Rollup,
  Row,
  Rows_per_resultset,
  Rows,
  Run_as_role,
  S3,
  Sample,
  Scaling_policy,
  Scheams,
  Schedule,
  Schema,
  Schemas,
  Scim_client,
  Scim,
  Search,
  Second,
  Secure,
  Security,
  Seed,
  Select,
  Semi,
  Sequence,
  Sequences,
  Session,
  Set,
  Sets,
  Setup,
  Share,
  Show,
  Simple,
  Simulated_data_sharing_consumer,
  Size_limit,
  Skip_blank_lines,
  Skip_byte_order_mark,
  Skip_file,
  Skip_header,
  Small,
  Snappy_compression,
  Snappy,
  Snowflake_support,
  Stage_copy_options,
  Stage_file_format,
  Stage,
  Stages,
  Standard,
  Start_timestamp,
  Start,
  Starts,
  Statement_queued_timeout_in_seconds,
  Statement_timeout_in_seconds,
  Statement,
  Storage_integration,
  Storage,
  Stream,
  Streams,
  Strict_json_output,
  Strict,
  String,
  Strip_null_values,
  Strip_outer_array,
  Strip_outer_element,
  Support,
  Supported,
  Suspend_immediate,
  Suspend,
  System,
  T,
  Table_name,
  Table,
  Tables,
  Tablesample,
  Tag,
  Task,
  Tasks,
  Temp,
  Template,
  Temporary,
  Terse,
  Text,
  Then,
  Time_format,
  Time_input_format,
  Time_output_format,
  Timestamp_day_is_always_24h,
  Timestamp_format,
  Timestamp_input_format,
  Timestamp_ltz_output_format,
  Timestamp_ltz,
  Timestamp_ntz_output_format,
  Timestamp_ntz,
  Timestamp_output_format,
  Timestamp_type_mapping,
  Timestamp_tz_output_format,
  Timestamp_tz,
  Timestamp,
  Timestampltz,
  Timestampntz,
  Timestamptz,
  Timezone,
  To,
  Top,
  Transaction_default_isolation_level,
  Transient,
  Triggers,
  Trim_space,
  True,
  Truncate,
  Truncatecolumns,
  Try_cast,
  Ts,
  Two_digit_century_start,
  Type,
  Unbounded,
  Union,
  Unique,
  Unpivot,
  Unsupported_ddl_action,
  Update,
  Url,
  Usage,
  Use_cached_result,
  Use,
  User_task_timeout_ms,
  User,
  Users,
  Using,
  Utf8,
  Validate_utf8,
  Validate,
  Values,
  Varbinary,
  Varchar,
  Varying,
  View,
  Views,
  Volatile,
  Volume,
  Volumes,
  Warehouse_size,
  Warehouse,
  Warehouses,
  Week_of_year_policy,
  Week_start,
  Weekly,
  When,
  Where,
  Windows,
  With,
  Without,
  Work,
  Write,
  X,
  X4large,
  Xlarge,
  Xml,
  Xsmall,
  Xxlarge,
  Xxxlarge,
  Year,
  Yearly,
  Zone,
  Zstd,
} from "./parser.terms.js";

const keywordTokens = {
  access: Access,
  activate: Activate,
  admin_name: Admin_name,
  admin_password: Admin_password,
  admin: Admin,
  after: After,
  all: All,
  allow_duplicate: Allow_duplicate,
  allowed_ip_list: Allowed_IP_List,
  and: And,
  any: Any,
  api_allowed_prefixes: Api_allowed_prefixes,
  api_aws_role_arn: Api_aws_role_arn,
  api_blocked_prefixes: Api_blocked_prefixes,
  api_integration: Api_integration,
  api_key: Api_key,
  api_provider: Api_provider,
  api: Api,
  applications: Applications,
  apply: Apply,
  as: As,
  asc: Asc,
  at: At,
  attach: Attach,
  auto_ingest: Auto_ingest,
  auto_refresh_materialized_views_on_secondary:
  Auto_refresh_materialized_views_on_secondary,
  auto_refresh: Auto_refresh,
  auto_resume: Auto_resume,
  auto_suspend: Auto_suspend,
  auto: Auto,
  autocommit: Autocommit,
  autoincrement: Autoincrement,
  avro: Avro,
  aws_api_gateway: Aws_api_gateway,
  aws_cse: Aws_cse,
  aws_key_id: Aws_key_id,
  aws_private_api_gateway: Aws_private_api_gateway,
  aws_role: Aws_role,
  aws_secret_key: Aws_secret_key,
  aws_sse_kms: Aws_sse_kms,
  aws_sse_s3: Aws_sse_s3,
  aws_token: Aws_token,
  azure_ad_application_id: Azure_ad_application_id,
  azure_api_management: Azure_api_management,
  azure_cse: Azure_cse,
  azure_sas_token: Azure_sas_token,
  azure_storage_queue_primary_uri: Azure_storage_queue_primary_uri,
  azure_storage_queue: Azure_storage_queue,
  azure_tenant_id: Azure_tenant_id,
  base64: Base64,
  before: Before,
  bernoulii: Bernoulli,
  between: Between,
  binary_as_text: Binary_as_text,
  binary_format: Binary_format,
  binary_input_format: Binary_input_format,
  binary_output_format: Binary_output_format,
  binary: Binary,
  blob: Blob,
  block: Block,
  blocked_ip_list: Blocked_IP_List,
  blocked_roles_list: Blocked_roles_list,
  bool: Bool,
  boolean: Boolean,
  brotli: Brotli,
  business_critical: Business_critical,
  business: Business,
  by: By,
  bz2: Bz2,
  called: Called,
  caller: Caller,
  cascade: Cascade,
  case_insensitive: Case_insensitive,
  case_sensitive: Case_sensitive,
  case: Case,
  cast: Cast,
  change_tracking: Change_tracking,
  change: Change,
  char: Char,
  character: Character,
  clone: Clone,
  cluster: Cluster,
  collate: Collate,
  compression: Compression,
  confidential: Confidential,
  connect_by_root: Connect_by_root,
  connect: Connect,
  connection: Connection,
  constraint: Constraint,
  context_headers: Context_headers,
  continue: Continue,
  copy_options: Copy_options,
  copy: Copy,
  copyoptions: Copyoptions,
  core: Core,
  create: Create,
  credential: Credential,
  credentials: Credentials,
  credit_quota: Credit_quota,
  critical: Critical,
  cron: Cron,
  cross: Cross,
  csv: Csv,
  cube: Cube,
  current: Current,
  custom: Custom,
  daily: Daily,
  data_retention_time_in_days: Data_retention_time_in_days,
  databases: Databases,
  date_format: Date_format,
  datetieme: Datetime,
  days_to_expiry: Days_to_expiry,
  dec: Dec,
  decimal: Decimal,
  default: Default,
  deferrable: Deferrable,
  Deferred: Deferred,
  deflate: Deflate,
  delete: Delete,
  desc: Desc,
  describe: Describe,
  disable_auto_convert: Disable_auto_convert,
  disable_snowflake_data: Disable_snowflake_data,
  disable: Disable,
  distinct: Distinct,
  div: Div,
  do: Do,
  drop: Drop,
  economy: Economy,
  edition: Edition,
  else: Else,
  email_address: Email_address,
  empty_field_as_null: Empty_field_as_null,
  enable_for_privilege: Enable_for_privilege,
  enable_octal: Enable_octal,
  enable: Enable,
  encoding: Encoding,
  end_timestamp: End_timestamp,
  end: End,
  endset: Endset,
  enforce_length: Enforce_length,
  enforced: Enforced,
  enterprise: Enterprise,
  error_on_column_count_mismatch: Error_on_column_count_mismatch,
  escape_unenclosed_field: Escape_unenclosed_field,
  escape: Escape,
  except: Except,
  exchange: Exchange,
  execute: Execute,
  execution: Execution,
  exists: Exists,
  extact: Extract,
  external: External,
  false: False,
  fetch: Fetch,
  field_delimiter: Field_delimiter,
  field_optionally_enclosed_by: Field_optionally_enclosed_by,
  file_extension: File_extension,
  file_format: File_format,
  file: File,
  first: First,
  fn: Fn,
  following: Following,
  for: For,
  force: Force,
  foreign: Foreign,
  format_name: Format_name,
  format: Format,
  formats: Formats,
  formattypeoptions: Formattypeoptions,
  frequency: Frequency,
  from: From,
  full: Full,
  function: Function,
  functions: Functions,
  future: Future,
  gcs_sse_kms: Gcs_sse_kms,
  generic_scim_provisioner: Generic_scim_provisioner,
  get: Get,
  global: Global,
  google_api_gateway: Google_api_gateway,
  google_audience: Google_audience,
  grant: Grant,
  grants: Grants,
  group: Group,
  group: Group,
  grouping: Grouping,
  gscluster: Gscluster,
  gzip: Gzip,
  having: Having,
  headers: Headers,
  hex: Hex,
  history: History,
  if: If,
  ignore_utf8_errors: Ignore_utf8_errors,
  ignoring: Ignoring,
  immediate: Immediate,
  immediate: Immediate,
  immediately: Immediately,
  immutable: Immutable,
  import: Import,
  imported: Imported,
  in: In,
  increment: Increment,
  initiallly: Initiallly,
  initially_suspended: Initially_suspended,
  inner: Inner,
  insert: Insert,
  integrations: Integrations,
  intersect: Intersect,
  into: Into,
  is: Is,
  join: Join,
  json_indent: Json_indent,
  json: Json,
  language: Language,
  large: Large,
  last: Last,
  lateral: Lateral,
  like: Like,
  limit: Limit,
  list: List,
  listing: Listing,
  local: Local,
  lock_timeout: Lock_timeout,
  lzo: Lzo,
  manage: Manage,
  managed: Managed,
  masking: Masking,
  master_key: Master_key,
  match_by_column_name: Match_by_column_name,
  match: Match,
  max_batch_rows: Max_batch_rows,
  max_cluster_count: Max_cluster_count,
  max_concurrency_level: Max_concurrency_level,
  max_data_extension_time_in_days: Max_data_extension_time_in_days,
  medium: Medium,
  min_cluster_count: Min_cluster_count,
  mins_to_bypass_mfa: Mins_to_bypass_mfa,
  mins_to_unlock: Mins_to_unlock,
  modify: Modify,
  monitor: Monitor,
  monitors: Monitors,
  monthly: Monthly,
  must: Must,
  natural: Natural,
  net: Net,
  network_policy: Network_policy,
  network: Network,
  networks: Networks,
  never: Never,
  next: Next,
  no: No,
  none: None,
  norely: Norely,
  not: Not,
  notification_provider: Notification_provider,
  notification: Notification,
  notify: Notify,
  novalidate: Novalidate,
  null_if: Null_if,
  nulls: Nulls,
  number: Number,
  numeric: Numeric,
  objects: Objects,
  of: Of,
  offset: Offset,
  oj: Oj,
  on_error: On_error,
  on: On,
  only: Only,
  operate: Operate,
  optimization: Optimization,
  option: Option,
  or: Or,
  orc: Orc,
  outer: Outer,
  over: Over,
  override: Override,
  overwrite: Overwrite,
  ownership: Ownership,
  pacread: Pacread,
  pacwrite: Pacwrite,
  parameters: Parameters,
  parquet: Parquet,
  partial: Partial,
  partition: Partition,
  pattern: Pattern,
  pipe: Pipe,
  pipes: Pipes,
  position: Position,
  pre_authorized_roles_list: Pre_authorized_roles_list,
  Preceding: Preceding,
  precsion: Precision,
  preserve_space: Preserve_space,
  primary: Primary,
  prior: Prior,
  privileges: Privileges,
  procedure: Procedure,
  procedures: Procedures,
  purge: Purge,
  qualify: Qualify,
  query_tag: Query_tag,
  range: Range,
  raw_deflate: Raw_deflate,
  read: Read,
  reader: Reader,
  rebuild: Rebuild,
  record_delimiter: Record_delimiter,
  recursive: Recursive,
  reference: Reference,
  references: References,
  refresh_on_create: Refresh_on_create,
  region_group: Region_group,
  release: Release,
  rely: Rely,
  repeatable: Repeatable,
  replace_invalid_characters: Replace_invalid_characters,
  replace: Replace,
  replica: Replica,
  replication: Replication,
  resource_monitor: Resource_monitor,
  resource: Resource,
  restrict: Restrict,
  restrictions: Restrictions,
  restrictions: Restrictions,
  return_failed_only: Return_failed_only,
  returns: Returns,
  revoke: Revoke,
  ribe: Ribe,
  right: Right,
  rollback: Rollback,
  rollup: Rollup,
  row: Row,
  rows_per_resultset: Rows_per_resultset,
  rows: Rows,
  run_as_role: Run_as_role,
  s3: S3,
  sample: Sample,
  scaling_policy: Scaling_policy,
  scheams: Scheams,
  schemas: Schemas,
  scim_client: Scim_client,
  scim: Scim,
  search: Search,
  second: Second,
  seed: Seed,
  select: Select,
  semi: Semi,
  sequence: Sequence,
  sequences: Sequences,
  session: Session,
  set: Set,
  sets: Sets,
  setup: Setup,
  share: Share,
  show: Show,
  simple: Simple,
  simulated_data_sharing_consumer: Simulated_data_sharing_consumer,
  size_limit: Size_limit,
  skip_blank_lines: Skip_blank_lines,
  skip_byte_order_mark: Skip_byte_order_mark,
  skip_file: Skip_file,
  skip_header: Skip_header,
  small: Small,
  snappy_compression: Snappy_compression,
  snappy: Snappy,
  snowflake_support: Snowflake_support,
  stage_copy_options: Stage_copy_options,
  stage_file_format: Stage_file_format,
  stages: Stages,
  standard: Standard,
  start_timestamp: Start_timestamp,
  start: Start,
  starts: Starts,
  statement_queued_timeout_in_seconds: Statement_queued_timeout_in_seconds,
  statement_timeout_in_seconds: Statement_timeout_in_seconds,
  statement: Statement,
  storage_integration: Storage_integration,
  storage: Storage,
  stream: Stream,
  streams: Streams,
  strict_json_output: Strict_json_output,
  strict: Strict,
  string: String,
  strip_null_values: Strip_null_values,
  strip_outer_array: Strip_outer_array,
  strip_outer_element: Strip_outer_element,
  support: Support,
  supported: Supported,
  suspend_immediate: Suspend_immediate,
  suspend: Suspend,
  system: System,
  t: T,
  table: Table,
  tables: Tables,
  tablesample: Tablesample,
  task: Task,
  tasks: Tasks,
  temp: Temp,
  template: Template,
  temporary: Temporary,
  terse: Terse,
  text: Text,
  then: Then,
  time_format: Time_format,
  time_input_format: Time_input_format,
  time_output_format: Time_output_format,
  timestamp_day_is_always_24h: Timestamp_day_is_always_24h,
  timestamp_format: Timestamp_format,
  timestamp_input_format: Timestamp_input_format,
  timestamp_ltz_output_format: Timestamp_ltz_output_format,
  timestamp_ltz: Timestamp_ltz,
  timestamp_ntz_output_format: Timestamp_ntz_output_format,
  timestamp_ntz: Timestamp_ntz,
  timestamp_output_format: Timestamp_output_format,
  timestamp_type_mapping: Timestamp_type_mapping,
  timestamp_tz_output_format: Timestamp_tz_output_format,
  timestamp_tz: Timestamp_tz,
  timestampltz: Timestampltz,
  timestampntz: Timestampntz,
  timestamptz: Timestamptz,
  timezone: Timezone,
  to: To,
  top: Top,
  transaction_default_isolation_level: Transaction_default_isolation_level,
  triggers: Triggers,
  trim_space: Trim_space,
  true: True,
  truncate: Truncate,
  truncatecolumns: Truncatecolumns,
  try_cast: Try_cast,
  ts: Ts,
  two_digit_century_start: Two_digit_century_start,
  undbounded: Unbounded,
  union: Union,
  unique: Unique,
  unpivot: Unpivot,
  unsupported_ddl_action: Unsupported_ddl_action,
  update: Update,
  usage: Usage,
  use_cached_result: Use_cached_result,
  use: Use,
  user_task_timeout_ms: User_task_timeout_ms,
  users: Users,
  using: Using,
  utf8: Utf8,
  validate_utf8: Validate_utf8,
  validate: Validate,
  values: Values,
  values: Values,
  varbinary: Varbinary,
  varchar: Varchar,
  varying: Varying,
  volatile: Volatile,
  volume: Volume,
  volumes: Volumes,
  warehouse_size: Warehouse_size,
  warehouses: Warehouses,
  week_of_year_policy: Week_of_year_policy,
  week_start: Week_start,
  weekly: Weekly,
  when: When,
  where: Where,
  windows: Windows,
  with: With,
  without: Without,
  work: Work,
  write: Write,
  x4large: X4large,
  xlarge: Xlarge,
  xml: Xml,
  xsmall: Xsmall,
  xxlarge: Xxlarge,
  xxxlarge: Xxxlarge,
  yearly: Yearly,
  zone: Zone,
  zstd: Zstd
};

export const specializeIdentifier = (value, stack) => {
  return keywordTokens[value.toLowerCase()] || -1;
};

const contextualKeywordTokens = {
  account: Account,
  action: Action,
  alter: Alter,
  application: Application,
  aws_sns_topic: Aws_sns_topic,
  azure: Azure,
  call: Call,
  channel: Channel,
  columns: Columns,
  comment: Comment,
  commit: Commit,
  d: D,
  data: Data,
  database: Database,
  day: Day,
  default_ddl_collation: Default_ddl_collation,
  default_namespace: Default_namespace,
  default_role: Default_role,
  default_warehouse: Default_warehouse,
  disabled: Disabled,
  display_name: Display_name,
  email: Email,
  enabled: Enabled,
  encryption: Encryption,
  first_name: First_name,
  gcs: Gcs,
  hour: Hour,
  identity: Identity,
  ilike: Ilike,
  index: Index,
  input: Input,
  integration: Integration,
  ip: Ip,
  key: Key,
  keys: Keys,
  kms_key_id: Kms_key_id,
  last_name: Last_name,
  left: Left,
  location: Location,
  login_name: Login_name,
  materialized: Materialized,
  middle_name: Middle_name,
  minute: Minute,
  month: Month,
  must_change_password: Must_change_password,
  name: Name,
  null: Null,
  okta: Okta,
  order: Order,
  organization: Organization,
  owner: Owner,
  password: Password,
  percent: Percent,
  policies: Policies,
  policy: Policy,
  profile: Profile,
  public: Public,
  queue: Queue,
  regexp: Regexp,
  region: Region,
  resume: Resume,
  role: Role,
  schedule: Schedule,
  schema: Schema,
  secure: Secure,
  security: Security,
  stage: Stage,
  table_name: Table_name,
  tag: Tag,
  text: Text,
  timestamp: Timestamp,
  transient: Transient,
  type: Type,
  url: Url,
  user: User,
  view: View,
  views: Views,
  warehouse: Warehouse,
  x: X,
  year: Year
};

export const extendIdentifier = (value, stack) => {
  return contextualKeywordTokens[value.toLowerCase()] || -1;
};
